schemaVersion: 2.1.0
attributes:
  controller.devfile.io/storage-type: ephemeral
  controller.devfile.io/scc: container-build
components:
  - name: tilt-container
    container:
      image: quay.io/mloriedo/universal-developer-image:buildah
      memoryLimit: 1G
      memoryRequest: 256Mi
      cpuLimit: 200m
      cpuRequest: 30m
